apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomo-api-service
spec:
  replicas: 1
  selector:
      matchLabels:
        app: tomo-api-service
  template:
    metadata:
      name: tomo-api-service
      labels:
        app: tomo-api-service
    spec:
      containers:
      - name: tomo-api-service
        image: {{.Values.dockerRegistryUrl}}/teliacompany/tlt/services/tomo-api-service:1.0.0-SNAPSHOT
        imagePullPolicy: {{.Values.imagePullPolicy}}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: tomo-api-service
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"